# Generated by Django 6.0.3 on 2026-03-21 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_user_otp_user_otp_create_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='otp_create_at',
            new_name='otp_created_at',
        ),
    ]
