# Generated by Django 6.0.3 on 2026-03-21 06:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_rename_otp_create_at_user_otp_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
